name: aviz
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pinput: ^3.0.1
  flutter_timer_countdown: ^1.0.7
  intl: ^0.19.0
  flutter_switch: ^0.3.2
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  linear_progress_bar: ^1.1.1


  get_it: ^7.6.7
  bloc: ^8.1.3
  dartz: ^0.10.1
  flutter_bloc: ^8.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  zarinpal: ^1.0.5
  uni_links: ^0.5.1
  url_launcher: ^6.2.5
  dio: ^5.4.1
  loading_indicator: ^3.1.1
  



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
